# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bot_base_pb2 as bot__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bot_event.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\021net.lz1998.botidl',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x62ot_event.proto\x1a\x0e\x62ot_base.proto\"\x90\x01\n\x05\x45vent\x12\r\n\x05\x62otId\x18\x01 \x01(\x03\x12\x1d\n\teventType\x18\x02 \x01(\x0e\x32\n.EventType\x12%\n\x0cgroupMessage\x18\x65 \x01(\x0b\x32\r.GroupMessageH\x00\x12)\n\x0eprivateMessage\x18\x66 \x01(\x0b\x32\x0f.PrivateMessageH\x00\x42\x07\n\x05\x65vent\"E\n\x0cGroupMessage\x12\x0f\n\x07groupId\x18\x01 \x01(\x03\x12\x13\n\x04user\x18\x02 \x01(\x0b\x32\x05.User\x12\x0f\n\x07message\x18\x03 \x01(\t\"6\n\x0ePrivateMessage\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\x12\x0f\n\x07message\x18\x02 \x01(\t*3\n\tEventType\x12\x13\n\x0fPRIVATE_MESSAGE\x10\x00\x12\x11\n\rGROUP_MESSAGE\x10\x01\x42\x13\n\x11net.lz1998.botidlb\x06proto3'
  ,
  dependencies=[bot__base__pb2.DESCRIPTOR,])

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='EventType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIVATE_MESSAGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GROUP_MESSAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=309,
  serialized_end=360,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
PRIVATE_MESSAGE = 0
GROUP_MESSAGE = 1



_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='botId', full_name='Event.botId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='Event.eventType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='groupMessage', full_name='Event.groupMessage', index=2,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='privateMessage', full_name='Event.privateMessage', index=3,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='Event.event',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=36,
  serialized_end=180,
)


_GROUPMESSAGE = _descriptor.Descriptor(
  name='GroupMessage',
  full_name='GroupMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupId', full_name='GroupMessage.groupId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='GroupMessage.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='GroupMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=251,
)


_PRIVATEMESSAGE = _descriptor.Descriptor(
  name='PrivateMessage',
  full_name='PrivateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='PrivateMessage.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='PrivateMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=307,
)

_EVENT.fields_by_name['eventType'].enum_type = _EVENTTYPE
_EVENT.fields_by_name['groupMessage'].message_type = _GROUPMESSAGE
_EVENT.fields_by_name['privateMessage'].message_type = _PRIVATEMESSAGE
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['groupMessage'])
_EVENT.fields_by_name['groupMessage'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['privateMessage'])
_EVENT.fields_by_name['privateMessage'].containing_oneof = _EVENT.oneofs_by_name['event']
_GROUPMESSAGE.fields_by_name['user'].message_type = bot__base__pb2._USER
_PRIVATEMESSAGE.fields_by_name['user'].message_type = bot__base__pb2._USER
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['GroupMessage'] = _GROUPMESSAGE
DESCRIPTOR.message_types_by_name['PrivateMessage'] = _PRIVATEMESSAGE
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'bot_event_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  })
_sym_db.RegisterMessage(Event)

GroupMessage = _reflection.GeneratedProtocolMessageType('GroupMessage', (_message.Message,), {
  'DESCRIPTOR' : _GROUPMESSAGE,
  '__module__' : 'bot_event_pb2'
  # @@protoc_insertion_point(class_scope:GroupMessage)
  })
_sym_db.RegisterMessage(GroupMessage)

PrivateMessage = _reflection.GeneratedProtocolMessageType('PrivateMessage', (_message.Message,), {
  'DESCRIPTOR' : _PRIVATEMESSAGE,
  '__module__' : 'bot_event_pb2'
  # @@protoc_insertion_point(class_scope:PrivateMessage)
  })
_sym_db.RegisterMessage(PrivateMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
