// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package net.lz1998.botidl;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * EVENT
   * 机器人收到 消息/请求/通知 后上报给服务端
   * 事件 是被动德发生的
   * </pre>
   *
   * Protobuf enum {@code EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PRIVATE_MESSAGE = 0;</code>
     */
    PRIVATE_MESSAGE(0),
    /**
     * <code>GROUP_MESSAGE = 1;</code>
     */
    GROUP_MESSAGE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PRIVATE_MESSAGE = 0;</code>
     */
    public static final int PRIVATE_MESSAGE_VALUE = 0;
    /**
     * <code>GROUP_MESSAGE = 1;</code>
     */
    public static final int GROUP_MESSAGE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return PRIVATE_MESSAGE;
        case 1: return GROUP_MESSAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.lz1998.botidl.Event.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EventType)
  }

  public interface BotEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BotEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 botId = 1;</code>
     * @return The botId.
     */
    long getBotId();

    /**
     * <code>.EventType eventType = 2;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    int getEventTypeValue();
    /**
     * <code>.EventType eventType = 2;</code>
     * @return The eventType.
     */
    net.lz1998.botidl.Event.EventType getEventType();

    /**
     * <code>.GroupMessage groupMessage = 101;</code>
     * @return Whether the groupMessage field is set.
     */
    boolean hasGroupMessage();
    /**
     * <code>.GroupMessage groupMessage = 101;</code>
     * @return The groupMessage.
     */
    net.lz1998.botidl.Event.GroupMessage getGroupMessage();
    /**
     * <code>.GroupMessage groupMessage = 101;</code>
     */
    net.lz1998.botidl.Event.GroupMessageOrBuilder getGroupMessageOrBuilder();

    /**
     * <code>.PrivateMessage privateMessage = 102;</code>
     * @return Whether the privateMessage field is set.
     */
    boolean hasPrivateMessage();
    /**
     * <code>.PrivateMessage privateMessage = 102;</code>
     * @return The privateMessage.
     */
    net.lz1998.botidl.Event.PrivateMessage getPrivateMessage();
    /**
     * <code>.PrivateMessage privateMessage = 102;</code>
     */
    net.lz1998.botidl.Event.PrivateMessageOrBuilder getPrivateMessageOrBuilder();

    public net.lz1998.botidl.Event.BotEvent.EventCase getEventCase();
  }
  /**
   * Protobuf type {@code BotEvent}
   */
  public static final class BotEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BotEvent)
      BotEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BotEvent.newBuilder() to construct.
    private BotEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BotEvent() {
      eventType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BotEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BotEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              botId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              eventType_ = rawValue;
              break;
            }
            case 810: {
              net.lz1998.botidl.Event.GroupMessage.Builder subBuilder = null;
              if (eventCase_ == 101) {
                subBuilder = ((net.lz1998.botidl.Event.GroupMessage) event_).toBuilder();
              }
              event_ =
                  input.readMessage(net.lz1998.botidl.Event.GroupMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((net.lz1998.botidl.Event.GroupMessage) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 101;
              break;
            }
            case 818: {
              net.lz1998.botidl.Event.PrivateMessage.Builder subBuilder = null;
              if (eventCase_ == 102) {
                subBuilder = ((net.lz1998.botidl.Event.PrivateMessage) event_).toBuilder();
              }
              event_ =
                  input.readMessage(net.lz1998.botidl.Event.PrivateMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((net.lz1998.botidl.Event.PrivateMessage) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 102;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.lz1998.botidl.Event.internal_static_BotEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.lz1998.botidl.Event.internal_static_BotEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.lz1998.botidl.Event.BotEvent.class, net.lz1998.botidl.Event.BotEvent.Builder.class);
    }

    private int eventCase_ = 0;
    private java.lang.Object event_;
    public enum EventCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      GROUPMESSAGE(101),
      PRIVATEMESSAGE(102),
      EVENT_NOT_SET(0);
      private final int value;
      private EventCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventCase valueOf(int value) {
        return forNumber(value);
      }

      public static EventCase forNumber(int value) {
        switch (value) {
          case 101: return GROUPMESSAGE;
          case 102: return PRIVATEMESSAGE;
          case 0: return EVENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EventCase
    getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public static final int BOTID_FIELD_NUMBER = 1;
    private long botId_;
    /**
     * <code>int64 botId = 1;</code>
     * @return The botId.
     */
    @java.lang.Override
    public long getBotId() {
      return botId_;
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 2;
    private int eventType_;
    /**
     * <code>.EventType eventType = 2;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.EventType eventType = 2;</code>
     * @return The eventType.
     */
    @java.lang.Override public net.lz1998.botidl.Event.EventType getEventType() {
      @SuppressWarnings("deprecation")
      net.lz1998.botidl.Event.EventType result = net.lz1998.botidl.Event.EventType.valueOf(eventType_);
      return result == null ? net.lz1998.botidl.Event.EventType.UNRECOGNIZED : result;
    }

    public static final int GROUPMESSAGE_FIELD_NUMBER = 101;
    /**
     * <code>.GroupMessage groupMessage = 101;</code>
     * @return Whether the groupMessage field is set.
     */
    @java.lang.Override
    public boolean hasGroupMessage() {
      return eventCase_ == 101;
    }
    /**
     * <code>.GroupMessage groupMessage = 101;</code>
     * @return The groupMessage.
     */
    @java.lang.Override
    public net.lz1998.botidl.Event.GroupMessage getGroupMessage() {
      if (eventCase_ == 101) {
         return (net.lz1998.botidl.Event.GroupMessage) event_;
      }
      return net.lz1998.botidl.Event.GroupMessage.getDefaultInstance();
    }
    /**
     * <code>.GroupMessage groupMessage = 101;</code>
     */
    @java.lang.Override
    public net.lz1998.botidl.Event.GroupMessageOrBuilder getGroupMessageOrBuilder() {
      if (eventCase_ == 101) {
         return (net.lz1998.botidl.Event.GroupMessage) event_;
      }
      return net.lz1998.botidl.Event.GroupMessage.getDefaultInstance();
    }

    public static final int PRIVATEMESSAGE_FIELD_NUMBER = 102;
    /**
     * <code>.PrivateMessage privateMessage = 102;</code>
     * @return Whether the privateMessage field is set.
     */
    @java.lang.Override
    public boolean hasPrivateMessage() {
      return eventCase_ == 102;
    }
    /**
     * <code>.PrivateMessage privateMessage = 102;</code>
     * @return The privateMessage.
     */
    @java.lang.Override
    public net.lz1998.botidl.Event.PrivateMessage getPrivateMessage() {
      if (eventCase_ == 102) {
         return (net.lz1998.botidl.Event.PrivateMessage) event_;
      }
      return net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance();
    }
    /**
     * <code>.PrivateMessage privateMessage = 102;</code>
     */
    @java.lang.Override
    public net.lz1998.botidl.Event.PrivateMessageOrBuilder getPrivateMessageOrBuilder() {
      if (eventCase_ == 102) {
         return (net.lz1998.botidl.Event.PrivateMessage) event_;
      }
      return net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (botId_ != 0L) {
        output.writeInt64(1, botId_);
      }
      if (eventType_ != net.lz1998.botidl.Event.EventType.PRIVATE_MESSAGE.getNumber()) {
        output.writeEnum(2, eventType_);
      }
      if (eventCase_ == 101) {
        output.writeMessage(101, (net.lz1998.botidl.Event.GroupMessage) event_);
      }
      if (eventCase_ == 102) {
        output.writeMessage(102, (net.lz1998.botidl.Event.PrivateMessage) event_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (botId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, botId_);
      }
      if (eventType_ != net.lz1998.botidl.Event.EventType.PRIVATE_MESSAGE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, eventType_);
      }
      if (eventCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, (net.lz1998.botidl.Event.GroupMessage) event_);
      }
      if (eventCase_ == 102) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, (net.lz1998.botidl.Event.PrivateMessage) event_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.lz1998.botidl.Event.BotEvent)) {
        return super.equals(obj);
      }
      net.lz1998.botidl.Event.BotEvent other = (net.lz1998.botidl.Event.BotEvent) obj;

      if (getBotId()
          != other.getBotId()) return false;
      if (eventType_ != other.eventType_) return false;
      if (!getEventCase().equals(other.getEventCase())) return false;
      switch (eventCase_) {
        case 101:
          if (!getGroupMessage()
              .equals(other.getGroupMessage())) return false;
          break;
        case 102:
          if (!getPrivateMessage()
              .equals(other.getPrivateMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBotId());
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + eventType_;
      switch (eventCase_) {
        case 101:
          hash = (37 * hash) + GROUPMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getGroupMessage().hashCode();
          break;
        case 102:
          hash = (37 * hash) + PRIVATEMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getPrivateMessage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.lz1998.botidl.Event.BotEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.BotEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.BotEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.BotEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.lz1998.botidl.Event.BotEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BotEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BotEvent)
        net.lz1998.botidl.Event.BotEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.lz1998.botidl.Event.internal_static_BotEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.lz1998.botidl.Event.internal_static_BotEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.lz1998.botidl.Event.BotEvent.class, net.lz1998.botidl.Event.BotEvent.Builder.class);
      }

      // Construct using net.lz1998.botidl.Event.BotEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        botId_ = 0L;

        eventType_ = 0;

        eventCase_ = 0;
        event_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.lz1998.botidl.Event.internal_static_BotEvent_descriptor;
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.BotEvent getDefaultInstanceForType() {
        return net.lz1998.botidl.Event.BotEvent.getDefaultInstance();
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.BotEvent build() {
        net.lz1998.botidl.Event.BotEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.BotEvent buildPartial() {
        net.lz1998.botidl.Event.BotEvent result = new net.lz1998.botidl.Event.BotEvent(this);
        result.botId_ = botId_;
        result.eventType_ = eventType_;
        if (eventCase_ == 101) {
          if (groupMessageBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = groupMessageBuilder_.build();
          }
        }
        if (eventCase_ == 102) {
          if (privateMessageBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = privateMessageBuilder_.build();
          }
        }
        result.eventCase_ = eventCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.lz1998.botidl.Event.BotEvent) {
          return mergeFrom((net.lz1998.botidl.Event.BotEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.lz1998.botidl.Event.BotEvent other) {
        if (other == net.lz1998.botidl.Event.BotEvent.getDefaultInstance()) return this;
        if (other.getBotId() != 0L) {
          setBotId(other.getBotId());
        }
        if (other.eventType_ != 0) {
          setEventTypeValue(other.getEventTypeValue());
        }
        switch (other.getEventCase()) {
          case GROUPMESSAGE: {
            mergeGroupMessage(other.getGroupMessage());
            break;
          }
          case PRIVATEMESSAGE: {
            mergePrivateMessage(other.getPrivateMessage());
            break;
          }
          case EVENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.lz1998.botidl.Event.BotEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.lz1998.botidl.Event.BotEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int eventCase_ = 0;
      private java.lang.Object event_;
      public EventCase
          getEventCase() {
        return EventCase.forNumber(
            eventCase_);
      }

      public Builder clearEvent() {
        eventCase_ = 0;
        event_ = null;
        onChanged();
        return this;
      }


      private long botId_ ;
      /**
       * <code>int64 botId = 1;</code>
       * @return The botId.
       */
      @java.lang.Override
      public long getBotId() {
        return botId_;
      }
      /**
       * <code>int64 botId = 1;</code>
       * @param value The botId to set.
       * @return This builder for chaining.
       */
      public Builder setBotId(long value) {
        
        botId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 botId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBotId() {
        
        botId_ = 0L;
        onChanged();
        return this;
      }

      private int eventType_ = 0;
      /**
       * <code>.EventType eventType = 2;</code>
       * @return The enum numeric value on the wire for eventType.
       */
      @java.lang.Override public int getEventTypeValue() {
        return eventType_;
      }
      /**
       * <code>.EventType eventType = 2;</code>
       * @param value The enum numeric value on the wire for eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventTypeValue(int value) {
        
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.EventType eventType = 2;</code>
       * @return The eventType.
       */
      @java.lang.Override
      public net.lz1998.botidl.Event.EventType getEventType() {
        @SuppressWarnings("deprecation")
        net.lz1998.botidl.Event.EventType result = net.lz1998.botidl.Event.EventType.valueOf(eventType_);
        return result == null ? net.lz1998.botidl.Event.EventType.UNRECOGNIZED : result;
      }
      /**
       * <code>.EventType eventType = 2;</code>
       * @param value The eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventType(net.lz1998.botidl.Event.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.EventType eventType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventType() {
        
        eventType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          net.lz1998.botidl.Event.GroupMessage, net.lz1998.botidl.Event.GroupMessage.Builder, net.lz1998.botidl.Event.GroupMessageOrBuilder> groupMessageBuilder_;
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       * @return Whether the groupMessage field is set.
       */
      @java.lang.Override
      public boolean hasGroupMessage() {
        return eventCase_ == 101;
      }
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       * @return The groupMessage.
       */
      @java.lang.Override
      public net.lz1998.botidl.Event.GroupMessage getGroupMessage() {
        if (groupMessageBuilder_ == null) {
          if (eventCase_ == 101) {
            return (net.lz1998.botidl.Event.GroupMessage) event_;
          }
          return net.lz1998.botidl.Event.GroupMessage.getDefaultInstance();
        } else {
          if (eventCase_ == 101) {
            return groupMessageBuilder_.getMessage();
          }
          return net.lz1998.botidl.Event.GroupMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       */
      public Builder setGroupMessage(net.lz1998.botidl.Event.GroupMessage value) {
        if (groupMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          groupMessageBuilder_.setMessage(value);
        }
        eventCase_ = 101;
        return this;
      }
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       */
      public Builder setGroupMessage(
          net.lz1998.botidl.Event.GroupMessage.Builder builderForValue) {
        if (groupMessageBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          groupMessageBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 101;
        return this;
      }
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       */
      public Builder mergeGroupMessage(net.lz1998.botidl.Event.GroupMessage value) {
        if (groupMessageBuilder_ == null) {
          if (eventCase_ == 101 &&
              event_ != net.lz1998.botidl.Event.GroupMessage.getDefaultInstance()) {
            event_ = net.lz1998.botidl.Event.GroupMessage.newBuilder((net.lz1998.botidl.Event.GroupMessage) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 101) {
            groupMessageBuilder_.mergeFrom(value);
          }
          groupMessageBuilder_.setMessage(value);
        }
        eventCase_ = 101;
        return this;
      }
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       */
      public Builder clearGroupMessage() {
        if (groupMessageBuilder_ == null) {
          if (eventCase_ == 101) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 101) {
            eventCase_ = 0;
            event_ = null;
          }
          groupMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       */
      public net.lz1998.botidl.Event.GroupMessage.Builder getGroupMessageBuilder() {
        return getGroupMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       */
      @java.lang.Override
      public net.lz1998.botidl.Event.GroupMessageOrBuilder getGroupMessageOrBuilder() {
        if ((eventCase_ == 101) && (groupMessageBuilder_ != null)) {
          return groupMessageBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 101) {
            return (net.lz1998.botidl.Event.GroupMessage) event_;
          }
          return net.lz1998.botidl.Event.GroupMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.GroupMessage groupMessage = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.lz1998.botidl.Event.GroupMessage, net.lz1998.botidl.Event.GroupMessage.Builder, net.lz1998.botidl.Event.GroupMessageOrBuilder> 
          getGroupMessageFieldBuilder() {
        if (groupMessageBuilder_ == null) {
          if (!(eventCase_ == 101)) {
            event_ = net.lz1998.botidl.Event.GroupMessage.getDefaultInstance();
          }
          groupMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.lz1998.botidl.Event.GroupMessage, net.lz1998.botidl.Event.GroupMessage.Builder, net.lz1998.botidl.Event.GroupMessageOrBuilder>(
                  (net.lz1998.botidl.Event.GroupMessage) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 101;
        onChanged();;
        return groupMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          net.lz1998.botidl.Event.PrivateMessage, net.lz1998.botidl.Event.PrivateMessage.Builder, net.lz1998.botidl.Event.PrivateMessageOrBuilder> privateMessageBuilder_;
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       * @return Whether the privateMessage field is set.
       */
      @java.lang.Override
      public boolean hasPrivateMessage() {
        return eventCase_ == 102;
      }
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       * @return The privateMessage.
       */
      @java.lang.Override
      public net.lz1998.botidl.Event.PrivateMessage getPrivateMessage() {
        if (privateMessageBuilder_ == null) {
          if (eventCase_ == 102) {
            return (net.lz1998.botidl.Event.PrivateMessage) event_;
          }
          return net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance();
        } else {
          if (eventCase_ == 102) {
            return privateMessageBuilder_.getMessage();
          }
          return net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       */
      public Builder setPrivateMessage(net.lz1998.botidl.Event.PrivateMessage value) {
        if (privateMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          privateMessageBuilder_.setMessage(value);
        }
        eventCase_ = 102;
        return this;
      }
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       */
      public Builder setPrivateMessage(
          net.lz1998.botidl.Event.PrivateMessage.Builder builderForValue) {
        if (privateMessageBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          privateMessageBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 102;
        return this;
      }
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       */
      public Builder mergePrivateMessage(net.lz1998.botidl.Event.PrivateMessage value) {
        if (privateMessageBuilder_ == null) {
          if (eventCase_ == 102 &&
              event_ != net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance()) {
            event_ = net.lz1998.botidl.Event.PrivateMessage.newBuilder((net.lz1998.botidl.Event.PrivateMessage) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 102) {
            privateMessageBuilder_.mergeFrom(value);
          }
          privateMessageBuilder_.setMessage(value);
        }
        eventCase_ = 102;
        return this;
      }
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       */
      public Builder clearPrivateMessage() {
        if (privateMessageBuilder_ == null) {
          if (eventCase_ == 102) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 102) {
            eventCase_ = 0;
            event_ = null;
          }
          privateMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       */
      public net.lz1998.botidl.Event.PrivateMessage.Builder getPrivateMessageBuilder() {
        return getPrivateMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       */
      @java.lang.Override
      public net.lz1998.botidl.Event.PrivateMessageOrBuilder getPrivateMessageOrBuilder() {
        if ((eventCase_ == 102) && (privateMessageBuilder_ != null)) {
          return privateMessageBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 102) {
            return (net.lz1998.botidl.Event.PrivateMessage) event_;
          }
          return net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.PrivateMessage privateMessage = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.lz1998.botidl.Event.PrivateMessage, net.lz1998.botidl.Event.PrivateMessage.Builder, net.lz1998.botidl.Event.PrivateMessageOrBuilder> 
          getPrivateMessageFieldBuilder() {
        if (privateMessageBuilder_ == null) {
          if (!(eventCase_ == 102)) {
            event_ = net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance();
          }
          privateMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.lz1998.botidl.Event.PrivateMessage, net.lz1998.botidl.Event.PrivateMessage.Builder, net.lz1998.botidl.Event.PrivateMessageOrBuilder>(
                  (net.lz1998.botidl.Event.PrivateMessage) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 102;
        onChanged();;
        return privateMessageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BotEvent)
    }

    // @@protoc_insertion_point(class_scope:BotEvent)
    private static final net.lz1998.botidl.Event.BotEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.lz1998.botidl.Event.BotEvent();
    }

    public static net.lz1998.botidl.Event.BotEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BotEvent>
        PARSER = new com.google.protobuf.AbstractParser<BotEvent>() {
      @java.lang.Override
      public BotEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BotEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BotEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BotEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.lz1998.botidl.Event.BotEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GroupMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GroupMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 groupId = 1;</code>
     * @return The groupId.
     */
    long getGroupId();

    /**
     * <code>.User user = 2;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>.User user = 2;</code>
     * @return The user.
     */
    net.lz1998.botidl.Base.User getUser();
    /**
     * <code>.User user = 2;</code>
     */
    net.lz1998.botidl.Base.UserOrBuilder getUserOrBuilder();

    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * 收到群消息
   * </pre>
   *
   * Protobuf type {@code GroupMessage}
   */
  public static final class GroupMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GroupMessage)
      GroupMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GroupMessage.newBuilder() to construct.
    private GroupMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupMessage() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GroupMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GroupMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              groupId_ = input.readInt64();
              break;
            }
            case 18: {
              net.lz1998.botidl.Base.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(net.lz1998.botidl.Base.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.lz1998.botidl.Event.internal_static_GroupMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.lz1998.botidl.Event.internal_static_GroupMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.lz1998.botidl.Event.GroupMessage.class, net.lz1998.botidl.Event.GroupMessage.Builder.class);
    }

    public static final int GROUPID_FIELD_NUMBER = 1;
    private long groupId_;
    /**
     * <code>int64 groupId = 1;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public long getGroupId() {
      return groupId_;
    }

    public static final int USER_FIELD_NUMBER = 2;
    private net.lz1998.botidl.Base.User user_;
    /**
     * <code>.User user = 2;</code>
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.User user = 2;</code>
     * @return The user.
     */
    @java.lang.Override
    public net.lz1998.botidl.Base.User getUser() {
      return user_ == null ? net.lz1998.botidl.Base.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.User user = 2;</code>
     */
    @java.lang.Override
    public net.lz1998.botidl.Base.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (groupId_ != 0L) {
        output.writeInt64(1, groupId_);
      }
      if (user_ != null) {
        output.writeMessage(2, getUser());
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (groupId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, groupId_);
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUser());
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.lz1998.botidl.Event.GroupMessage)) {
        return super.equals(obj);
      }
      net.lz1998.botidl.Event.GroupMessage other = (net.lz1998.botidl.Event.GroupMessage) obj;

      if (getGroupId()
          != other.getGroupId()) return false;
      if (hasUser() != other.hasUser()) return false;
      if (hasUser()) {
        if (!getUser()
            .equals(other.getUser())) return false;
      }
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupId());
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.lz1998.botidl.Event.GroupMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.GroupMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.lz1998.botidl.Event.GroupMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 收到群消息
     * </pre>
     *
     * Protobuf type {@code GroupMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GroupMessage)
        net.lz1998.botidl.Event.GroupMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.lz1998.botidl.Event.internal_static_GroupMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.lz1998.botidl.Event.internal_static_GroupMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.lz1998.botidl.Event.GroupMessage.class, net.lz1998.botidl.Event.GroupMessage.Builder.class);
      }

      // Construct using net.lz1998.botidl.Event.GroupMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        groupId_ = 0L;

        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.lz1998.botidl.Event.internal_static_GroupMessage_descriptor;
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.GroupMessage getDefaultInstanceForType() {
        return net.lz1998.botidl.Event.GroupMessage.getDefaultInstance();
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.GroupMessage build() {
        net.lz1998.botidl.Event.GroupMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.GroupMessage buildPartial() {
        net.lz1998.botidl.Event.GroupMessage result = new net.lz1998.botidl.Event.GroupMessage(this);
        result.groupId_ = groupId_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.lz1998.botidl.Event.GroupMessage) {
          return mergeFrom((net.lz1998.botidl.Event.GroupMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.lz1998.botidl.Event.GroupMessage other) {
        if (other == net.lz1998.botidl.Event.GroupMessage.getDefaultInstance()) return this;
        if (other.getGroupId() != 0L) {
          setGroupId(other.getGroupId());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.lz1998.botidl.Event.GroupMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.lz1998.botidl.Event.GroupMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long groupId_ ;
      /**
       * <code>int64 groupId = 1;</code>
       * @return The groupId.
       */
      @java.lang.Override
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>int64 groupId = 1;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(long value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 groupId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = 0L;
        onChanged();
        return this;
      }

      private net.lz1998.botidl.Base.User user_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.lz1998.botidl.Base.User, net.lz1998.botidl.Base.User.Builder, net.lz1998.botidl.Base.UserOrBuilder> userBuilder_;
      /**
       * <code>.User user = 2;</code>
       * @return Whether the user field is set.
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.User user = 2;</code>
       * @return The user.
       */
      public net.lz1998.botidl.Base.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? net.lz1998.botidl.Base.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.User user = 2;</code>
       */
      public Builder setUser(net.lz1998.botidl.Base.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public Builder setUser(
          net.lz1998.botidl.Base.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public Builder mergeUser(net.lz1998.botidl.Base.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              net.lz1998.botidl.Base.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.User user = 2;</code>
       */
      public net.lz1998.botidl.Base.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.User user = 2;</code>
       */
      public net.lz1998.botidl.Base.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              net.lz1998.botidl.Base.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.User user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.lz1998.botidl.Base.User, net.lz1998.botidl.Base.User.Builder, net.lz1998.botidl.Base.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.lz1998.botidl.Base.User, net.lz1998.botidl.Base.User.Builder, net.lz1998.botidl.Base.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GroupMessage)
    }

    // @@protoc_insertion_point(class_scope:GroupMessage)
    private static final net.lz1998.botidl.Event.GroupMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.lz1998.botidl.Event.GroupMessage();
    }

    public static net.lz1998.botidl.Event.GroupMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupMessage>
        PARSER = new com.google.protobuf.AbstractParser<GroupMessage>() {
      @java.lang.Override
      public GroupMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.lz1998.botidl.Event.GroupMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PrivateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PrivateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.User user = 1;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>.User user = 1;</code>
     * @return The user.
     */
    net.lz1998.botidl.Base.User getUser();
    /**
     * <code>.User user = 1;</code>
     */
    net.lz1998.botidl.Base.UserOrBuilder getUserOrBuilder();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * 收到私聊消息
   * </pre>
   *
   * Protobuf type {@code PrivateMessage}
   */
  public static final class PrivateMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PrivateMessage)
      PrivateMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PrivateMessage.newBuilder() to construct.
    private PrivateMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PrivateMessage() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PrivateMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PrivateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.lz1998.botidl.Base.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(net.lz1998.botidl.Base.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.lz1998.botidl.Event.internal_static_PrivateMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.lz1998.botidl.Event.internal_static_PrivateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.lz1998.botidl.Event.PrivateMessage.class, net.lz1998.botidl.Event.PrivateMessage.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private net.lz1998.botidl.Base.User user_;
    /**
     * <code>.User user = 1;</code>
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.User user = 1;</code>
     * @return The user.
     */
    @java.lang.Override
    public net.lz1998.botidl.Base.User getUser() {
      return user_ == null ? net.lz1998.botidl.Base.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.User user = 1;</code>
     */
    @java.lang.Override
    public net.lz1998.botidl.Base.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.lz1998.botidl.Event.PrivateMessage)) {
        return super.equals(obj);
      }
      net.lz1998.botidl.Event.PrivateMessage other = (net.lz1998.botidl.Event.PrivateMessage) obj;

      if (hasUser() != other.hasUser()) return false;
      if (hasUser()) {
        if (!getUser()
            .equals(other.getUser())) return false;
      }
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.lz1998.botidl.Event.PrivateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.lz1998.botidl.Event.PrivateMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 收到私聊消息
     * </pre>
     *
     * Protobuf type {@code PrivateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PrivateMessage)
        net.lz1998.botidl.Event.PrivateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.lz1998.botidl.Event.internal_static_PrivateMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.lz1998.botidl.Event.internal_static_PrivateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.lz1998.botidl.Event.PrivateMessage.class, net.lz1998.botidl.Event.PrivateMessage.Builder.class);
      }

      // Construct using net.lz1998.botidl.Event.PrivateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.lz1998.botidl.Event.internal_static_PrivateMessage_descriptor;
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.PrivateMessage getDefaultInstanceForType() {
        return net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance();
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.PrivateMessage build() {
        net.lz1998.botidl.Event.PrivateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.lz1998.botidl.Event.PrivateMessage buildPartial() {
        net.lz1998.botidl.Event.PrivateMessage result = new net.lz1998.botidl.Event.PrivateMessage(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.lz1998.botidl.Event.PrivateMessage) {
          return mergeFrom((net.lz1998.botidl.Event.PrivateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.lz1998.botidl.Event.PrivateMessage other) {
        if (other == net.lz1998.botidl.Event.PrivateMessage.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.lz1998.botidl.Event.PrivateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.lz1998.botidl.Event.PrivateMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.lz1998.botidl.Base.User user_;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.lz1998.botidl.Base.User, net.lz1998.botidl.Base.User.Builder, net.lz1998.botidl.Base.UserOrBuilder> userBuilder_;
      /**
       * <code>.User user = 1;</code>
       * @return Whether the user field is set.
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.User user = 1;</code>
       * @return The user.
       */
      public net.lz1998.botidl.Base.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? net.lz1998.botidl.Base.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.User user = 1;</code>
       */
      public Builder setUser(net.lz1998.botidl.Base.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.User user = 1;</code>
       */
      public Builder setUser(
          net.lz1998.botidl.Base.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.User user = 1;</code>
       */
      public Builder mergeUser(net.lz1998.botidl.Base.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              net.lz1998.botidl.Base.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.User user = 1;</code>
       */
      public net.lz1998.botidl.Base.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.User user = 1;</code>
       */
      public net.lz1998.botidl.Base.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              net.lz1998.botidl.Base.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.User user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.lz1998.botidl.Base.User, net.lz1998.botidl.Base.User.Builder, net.lz1998.botidl.Base.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.lz1998.botidl.Base.User, net.lz1998.botidl.Base.User.Builder, net.lz1998.botidl.Base.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PrivateMessage)
    }

    // @@protoc_insertion_point(class_scope:PrivateMessage)
    private static final net.lz1998.botidl.Event.PrivateMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.lz1998.botidl.Event.PrivateMessage();
    }

    public static net.lz1998.botidl.Event.PrivateMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrivateMessage>
        PARSER = new com.google.protobuf.AbstractParser<PrivateMessage>() {
      @java.lang.Override
      public PrivateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PrivateMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PrivateMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PrivateMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.lz1998.botidl.Event.PrivateMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BotEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BotEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GroupMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrivateMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrivateMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\032\nbase.proto\"\223\001\n\010BotEvent\022\r" +
      "\n\005botId\030\001 \001(\003\022\035\n\teventType\030\002 \001(\0162\n.Event" +
      "Type\022%\n\014groupMessage\030e \001(\0132\r.GroupMessag" +
      "eH\000\022)\n\016privateMessage\030f \001(\0132\017.PrivateMes" +
      "sageH\000B\007\n\005event\"E\n\014GroupMessage\022\017\n\007group" +
      "Id\030\001 \001(\003\022\023\n\004user\030\002 \001(\0132\005.User\022\017\n\007message" +
      "\030\003 \001(\t\"6\n\016PrivateMessage\022\023\n\004user\030\001 \001(\0132\005" +
      ".User\022\017\n\007message\030\002 \001(\t*3\n\tEventType\022\023\n\017P" +
      "RIVATE_MESSAGE\020\000\022\021\n\rGROUP_MESSAGE\020\001B\023\n\021n" +
      "et.lz1998.botidlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.lz1998.botidl.Base.getDescriptor(),
        });
    internal_static_BotEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BotEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BotEvent_descriptor,
        new java.lang.String[] { "BotId", "EventType", "GroupMessage", "PrivateMessage", "Event", });
    internal_static_GroupMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GroupMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GroupMessage_descriptor,
        new java.lang.String[] { "GroupId", "User", "Message", });
    internal_static_PrivateMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PrivateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrivateMessage_descriptor,
        new java.lang.String[] { "User", "Message", });
    net.lz1998.botidl.Base.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
